ERROR    root:custom_decorators.py:33 An unexpected error occurred during 'test_delete_delay_endpoint': Invalid URL 'None/delay/2': No scheme supplied. Perhaps you meant https://None/delay/2?